name = "Tragically Falling"
author = "SwimMau5"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94c209fc8e62b4d5335f993ed05d0c0a174026d2c826ba26c8397f3139e9c482"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"
